apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hw
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-hw
  resources:
    requests:
      storage: 100M  