apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-hw
  namespace: homework
subjects:
- kind: ServiceAccount
  name: cd
  namespace: homework
roleRef:
  kind: Role 
  name: admin
  apiGroup: rbac.authorization.k8s.io